CREATE DATABASE tkorp_test;

USE tkorp_test;

CREATE TABLE person (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lastName VARCHAR(100) NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  phoneNumber VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);